[versions]
opentelemetry-instrumentation-alpha = "2.20.0-alpha"
opentelemetry-instrumentation-api = "2.20.0"
opentelemetry-semconv = "1.37.0"
opentelemetry = "1.55.0"
opentelemetry-semconv-alpha = "1.34.0-alpha"
opentelemetry-contrib = "1.49.0-alpha"
opentelemetry-android = "0.16.0-alpha"
opentelemetry-api = "1.55.0"

mockito = "5.18.0"
junit = "5.13.3"
byteBuddy = "1.17.6"
spotless = "8.0.0"
kotlin = "2.2.0"
coroutines-version = "1.9.0"
androidPlugin = "8.11.1"
junitKtx = "1.3.0"
autoService = "1.1.1"
owasp = "12.1.9"
aws-smithy-kotlin = "1.4.16"
http-instrumentation = "0.10.0-alpha"
okhttp = "5.1.0"

[libraries]
opentelemetry-platform-alpha = { module = "io.opentelemetry.instrumentation:opentelemetry-instrumentation-bom-alpha", version.ref = "opentelemetry-instrumentation-alpha" }
opentelemetry-platform = { module = "io.opentelemetry.instrumentation:opentelemetry-instrumentation-bom" }
androidx-navigation-fragment = "androidx.navigation:navigation-fragment:2.7.7"
androidx-core = "androidx.core:core:1.16.0"
androidx-annotation = "androidx.annotation:annotation:1.9.1"
androidx-lifecycle-process = "androidx.lifecycle:lifecycle-process:2.8.7"
androidx-preference-ktx = "androidx.preference:preference-ktx:1.2.1"
findbugs-jsr305 = "com.google.code.findbugs:jsr305:3.0.2"
byteBuddy = { module = "net.bytebuddy:byte-buddy", version.ref = "byteBuddy" }
opentelemetry-android = { module = "io.opentelemetry.android:android-agent", version.ref = "opentelemetry-android" }
opentelemetry-android-common = { module = "io.opentelemetry.android:common", version.ref = "opentelemetry-android" }
opentelemetry-android-session = { module = "io.opentelemetry.android:session", version.ref = "opentelemetry-android" }
opentelemetry-android-httpurlconnection = {module = "io.opentelemetry.android.instrumentation:httpurlconnection-library", version.ref = "opentelemetry-android"}
opentelemetry-android-httpurlconnection-agent = {module = "io.opentelemetry.android.instrumentation:httpurlconnection-agent", version.ref = "opentelemetry-android"}
opentelemetry-android-okhttp3 = {module = "io.opentelemetry.android.instrumentation:okhttp3-library", version.ref = "opentelemetry-android"}
opentelemetry-android-okhttp3-agent = {module = "io.opentelemetry.android.instrumentation:okhttp3-agent", version.ref = "opentelemetry-android"}
opentelemetry-android-sessions-instrumentation = {module = "io.opentelemetry.android.instrumentation:sessions", version.ref = "opentelemetry-android"}
opentelemetry-instrumentation-api = { module = "io.opentelemetry.instrumentation:opentelemetry-instrumentation-api", version.ref = "opentelemetry-instrumentation-api" }
opentelemetry-instrumentation-apiSemconv = { module = "io.opentelemetry.instrumentation:opentelemetry-instrumentation-api-incubator", version.ref = "opentelemetry-instrumentation-alpha" }
opentelemetry-semconv = { module = "io.opentelemetry.semconv:opentelemetry-semconv", version.ref = "opentelemetry-semconv" }
opentelemetry-semconv-incubating = { module = "io.opentelemetry.semconv:opentelemetry-semconv-incubating", version.ref = "opentelemetry-semconv-alpha" }
opentelemetry-api = { module = "io.opentelemetry:opentelemetry-api", version.ref = "opentelemetry-api" }
opentelemetry-api-incubator = { module = "io.opentelemetry:opentelemetry-api-incubator" }
opentelemetry-sdk-extension-incubator = { module = "io.opentelemetry:opentelemetry-sdk-extension-incubator" }
opentelemetry-sdk = { module = "io.opentelemetry:opentelemetry-sdk", version.ref = "opentelemetry" }
opentelemetry-context = { module = "io.opentelemetry:opentelemetry-context" }
opentelemetry-exporter-logging = { module = "io.opentelemetry:opentelemetry-exporter-logging" }
opentelemetry-diskBuffering = { module = "io.opentelemetry.contrib:opentelemetry-disk-buffering", version.ref = "opentelemetry-contrib" }
opentelemetry-exporter-otlp = { module = "io.opentelemetry:opentelemetry-exporter-otlp", version.ref = "opentelemetry" }
opentelemetry-exporter-otlp-common = { module = "io.opentelemetry:opentelemetry-exporter-otlp-common", version.ref = "opentelemetry" }
volley = "com.android.volley:volley:1.2.1"
auto-service-annotations = { module = "com.google.auto.service:auto-service-annotations", version.ref = "autoService" }
auto-service-processor = { module = "com.google.auto.service:auto-service", version.ref = "autoService" }
aws-smithy-kotlin-aws-credentials = { module = "aws.smithy.kotlin:aws-credentials", version.ref = "aws-smithy-kotlin" }
aws-smithy-kotlin-aws-signing-default = { module = "aws.smithy.kotlin:aws-signing-default", version.ref = "aws-smithy-kotlin" }
aws-smithy-kotlin-http-auth-api = { module = "aws.smithy.kotlin:http-auth-api", version.ref = "aws-smithy-kotlin" }
aws-smithy-kotlin-http-auth-aws = { module = "aws.smithy.kotlin:http-auth-aws", version.ref = "aws-smithy-kotlin" }
serialization = {module= "org.jetbrains.kotlinx:kotlinx-serialization-json", version="1.8.0"}
okhttp3 = {module = "com.squareup.okhttp3:okhttp", version.ref="okhttp"}


#Test tools
opentelemetry-sdk-testing = { module = "io.opentelemetry:opentelemetry-sdk-testing", version = "1.49.0" }
androidx-test-core = "androidx.test:core:1.7.0"
androidx-test-rules = "androidx.test:rules:1.7.0"
androidx-test-runner = "androidx.test:runner:1.6.2"
androidx-junit = "androidx.test.ext:junit:1.2.1"
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito" }
mockito-junit-jupiter = { module = "org.mockito:mockito-junit-jupiter", version.ref = "mockito" }
mockk = "io.mockk:mockk:1.13.17"
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }
junit-vintage-engine = { module = "org.junit.vintage:junit-vintage-engine", version.ref = "junit" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher", version = "1.12.1" }
robolectric = "org.robolectric:robolectric:4.14.1"
assertj-core = "org.assertj:assertj-core:3.27.3"
awaitility = "org.awaitility:awaitility:4.3.0"
mockwebserver = "com.google.mockwebserver:mockwebserver:20130706"
owasp = {module = "org.owasp:dependency-check-gradle", version.ref = "owasp"}

#Compilation tools
desugarJdkLibs = "com.android.tools:desugar_jdk_libs:2.1.5"
nullaway = "com.uber.nullaway:nullaway:0.12.7"
errorprone-core = "com.google.errorprone:error_prone_core:2.37.0"
errorprone-javac = "com.google.errorprone:javac:1+"
spotless-plugin = { module = "com.diffplug.spotless:spotless-plugin-gradle", version.ref = "spotless" }
errorprone-plugin = "net.ltgt.gradle:gradle-errorprone-plugin:4.3.0"
nullaway-plugin = "net.ltgt.gradle:gradle-nullaway-plugin:2.2.0"
animalsniffer-plugin = "ru.vyarus:gradle-animalsniffer-plugin:2.0.0"
android-plugin = { module = "com.android.tools.build:gradle", version.ref = "androidPlugin" }
byteBuddy-plugin = { module = "net.bytebuddy:byte-buddy-gradle-plugin", version.ref = "byteBuddy" }
kotlin-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
androidx-junit-ktx = { group = "androidx.test.ext", name = "junit-ktx", version.ref = "junitKtx" }

kotlinx-coroutines-debug = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-debug", version.ref = "coroutines-version" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines-version" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines-version" }

[bundles]
mocking = ["mockito-core", "mockito-junit-jupiter", "mockk"]
junit = ["junit-jupiter-api", "junit-jupiter-engine", "junit-vintage-engine"]

[plugins]
publishPlugin = { id = "io.github.gradle-nexus.publish-plugin", version = "2.0.0" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
androidApp = { id = "com.android.application", version.ref = "androidPlugin" }